# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rerun'
gem 'roda'
gem 'puma'
gem 'awesome_print'
gem 'dotenv'

gem 'teneo-data_model'
gem 'teneo-ingester'
gem 'docker-api'
gem 'docker-compose'
gem 'rake'
