default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("DB_POOL_SIZE") { 5 } %>

  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT']&.to_i || 5432 %>

  dba_name: <%= ENV.fetch("DBA_USER") { 'teneo_dba' } %>
  dba_pass: <%= ENV.fetch("DBA_PASSWORD") { 'teneo_dba' } %>

  username: <%= ENV.fetch("DB_USER") { 'teneo' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'teneo' } %>

  data_schema: <%= ENV.fetch("DB_USER") { 'teneo' } %>
  schema_search_path: <%= ENV.fetch("DB_USER") { 'teneo' } %>, public

  migrations_paths: <%= Teneo::IngestServer.migrations_path %>

  dba_migrations_paths: <%= Teneo::IngestServer.dba_migrations_path %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'teneo_dev' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'teneo_test' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'teneo' %>
