version: "3.7"

services:

  worker:
    image: teneo/worker
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bundle-gems:/bundle-gems
      - oracle-client:/oracle-client

networks:
  frontend:
  backend:

volumes:
  db-data:
  bundle-gems:
  oracle-client:
